### PR TITLE
Use HTTPS for API requests

### PR DESCRIPTION
**Pull request by jcassee**
This is an fix for kennedyoliveira/ultimate-pastebin-intellij-plugin#3. The goal is to use HTTPS whenever possible.

### CODE REVIEW

**Comment by jcassee** [comment]
Interestingly, I only added `https://` to the API URLs, things just seem to work. Some tests fail when I use a non-PRO user, but also happens on the master branch.

I have found that Pastebin will redirect to HTTP sometimes for non-PRO users, but ran tcpdump/tcpflow during testing and saw no redirects. Probably they only check web requests for PRO-ness.

I changed the of the constant `PASTEBIN_URL` to;`PASTEBIN_RESULT_URL` because that seemed more descriptive now that we use HTTPS for posting.

**Comment by kennedyoliveira** [comment]
Humm maybe they doesn't redirect when is request for the API? If not, would be better to check if is a pro user doing the request and switch to HTTPS, and if not stay with HTTP for default.

There are a use case when HTTPS must not be used, posting as Guest, it will ever use HTTP since the Guest is not a PRO.

**Comment by jcassee** [comment]
Well, what I meant was, even when I test using a non-PRO account, it will post over HTTPS succesfully. Are you sure Pastebin enforces HTTP for non-PRO accounts?

**Comment by kennedyoliveira** [comment]
@jcassee, did some test here and yes, you are right, the API urls can be acesses via HTTPS even by non PRO users, it just redirect if you access the site as a non pro user.

I'm trying to understand why the tests are failing, when i run in my machine, sometimes it works other not, crazy pastebin lol, anyway i'm gonna merge your pull request because it seems to work.

I'm gonna work in this tests maybe today latter at home.

Thank you!

**Comment by kennedyoliveira** [comment]
the merge commit build worked without problem, lol what the hell did just happen

**Comment by jcassee** [comment]
Weird? Maybe it's the rate limiting? This sort of thing does happen when you need to test against an external service.

When could this change find its way to the IntelliJ plugin? :wink:

**Comment by kennedyoliveira** [comment]
Yeah very weird, uses the same user for testing, and shouldn't be the rate limit, pastebin limits are per day basis.

Anyway, yeah, i'll update the plugin wen i get home, now i'm at work and very busy.

**Comment by jcassee** [comment]
Great, thanks for taking the time to process my changes.

**Comment by kennedyoliveira** [comment]
Your welcome, i thank you for pointing this mistake and fixing it :D, by the way, i updated the plugin, check it out.

**Comment by jcassee** [comment]
Works great, thanks!

**Pull request merged**
